name: Actions Workflow

on: [push, pull_request]

jobs:
  run-github-actions:
      runs-on: ubuntu-latest
      steps: 
        - name: Simple JS Actions
          id: greet
          uses: actions/hello-world-javascript-action@v1
          with: 
            who-to-greet: Kavya
        - name: log Greeting time
          run: echo "${{steps.greet.outputs.time}}"
        - name: List Files
          run:  |
            pwd
            ls -a
            echo $GITHUB_SHA
            echo $GITHUB_REPOSITORY
            echo $"{{ github.token }}"
            echo $GITHUB_WORKSPACE
        - name: Checkout
          uses: actions/checkout@v1 
        - name: List of files after checkout
          run: |
            pwd
            ls -a    
