name: Shell Commands

on: [push,pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run : echo "Hello Github workflow"
      - name: multiline Scrpit
        run: |
          node -v
          npm -v
            